spring:
    jpa.hibernate.ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/EventsServer?createDatabaseIfNotExist=true
        username: root
        password: toor
        hikari:
            connecion-timeout: 60000
            maximum-pool-size: 5
server: 
    port: 8089
    
logging:
  level:
    root: INFO
  file:
    name: C:\logs\Events.log
    max-size: 1MB
    max-history: 10
    total-size-cap: 10MB

reaktor:
  publicKeyFile: C:\claves\public_key.pem
  urlCors: http://localhost:5173, http://192.168.1.209:5173, http://192.168.1.181:5173, http://192.168.1.137:5173, http://172.20.10.2:5173, http://localhost:5175
  firebase_server_url: http://localhost:8089
  clientId: events
  http_connection_timeout: 30000
  reiniciarParametros: true
